#include "ZFUIDialogContentBasic_Buttons.h"

ZF_NAMESPACE_GLOBAL_BEGIN

ZFSTYLE_DEFAULT_DEFINE(ZFUIDialogContentBasicButtonYes)
ZFOBJECT_REGISTER(ZFUIDialogContentBasicButtonYes)

ZFSTYLE_DEFAULT_DEFINE(ZFUIDialogContentBasicButtonNo)
ZFOBJECT_REGISTER(ZFUIDialogContentBasicButtonNo)

ZFSTYLE_DEFAULT_DEFINE(ZFUIDialogContentBasicButtonCancel)
ZFOBJECT_REGISTER(ZFUIDialogContentBasicButtonCancel)

ZFSTYLE_DEFAULT_DEFINE(ZFUIDialogContentBasicButtonDestructive)
ZFOBJECT_REGISTER(ZFUIDialogContentBasicButtonDestructive)

ZF_NAMESPACE_GLOBAL_END

