#include "ZFIterable.h"

ZF_NAMESPACE_GLOBAL_BEGIN

ZFOBJECT_REGISTER(ZFIterable)
ZFOBJECT_REGISTER(ZFIterableEditable)
ZFOBJECT_REGISTER(ZFIterableKeyValue)
ZFOBJECT_REGISTER(ZFIterableKeyValueEditable)

ZF_NAMESPACE_GLOBAL_END

